spring.application.name=admin
# configuración para la conexión a la base de datos
spring.datasource.url= jdbc:postgresql://localhost:5432/nicosound
spring.datasource.username=postgres
spring.datasource.password=marceko12@

# configuraciones de HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

